version: "3"

services:
  app:
     build:
       context: .
     ports:
       - "8020:8020"
     volumes:
       - ./app:/app
     command: >
        sh -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8020"

